### ISSUE TITLE
没有config.json文件

### ISSUE THREAD

**Issue by dulunar** [NN708/seu-wlan-login#1]
想咨询一下这个文件的格式是值还是对象？
谢谢；

然后我看了一下login_url好像是jlh的？那么牌区的呢？
谢谢！

**Comment by NN708** [comment]
你好 @dulunar，

配置文件是以 JSON 格式存储的。当程序发现目录下没有 config.json 时，它会自动生成一个。你只需要用文本编辑器打开它，在引号内填写你一卡通号和密码就可以了。

对于 login_url 的问题，如果在四牌楼校区使用，需要手动将 `jlh` 改为 `spl`。按理说，应该有办法根据网络环境自动判断当前校区（登录系统能做到根据校区自动填写），但我目前没有找到相应的接口，如果你有新的发现，欢迎提交 Pull Request。

**Comment by Sciroccogti** [comment]
> 你好 @dulunar，
> 
> 配置文件是以 JSON 格式存储的。当程序发现目录下没有 config.json 时，它会自动生成一个。你只需要用文本编辑器打开它，在引号内填写你一卡通号和密码就可以了。
> 
> 对于 login_url 的问题，如果在四牌楼校区使用，需要手动将 jlh 改为 sql。按理说，应该有办法根据网络环境自动判断当前校区（登录系统能做到根据校区自动填写），但我目前没有找到相应的接口，如果你有新的发现，欢迎提交 Pull Request。

应该是`spl`而不是`sql`吧。。大佬一看就是最近修sql修多了（逃

**Comment by NN708** [comment]
啊，我错了:joy:

**Comment by NN708** [comment]
这个 Issue 就先关闭了，如有需要可随时重新打开。
