### ISSUE TITLE
现在无法使用了

### ISSUE THREAD

**Issue by XinkaiJi** [NN708/seu-wlan-login#2]
现在无法使用了，是因为网络升级了吗

**Comment by NN708** [comment]
应该是的，我这两天找时间修复一下

**Comment by NN708** [comment]
@XinkaiJi 已在 f4bca31 中进行了修复，是否解决了你的问题？

**Comment by NN708** [comment]
这个 Issue 就先关闭了，如有需要可随时重新打开。
